package cn.zhou.path.model;

import cn.zhou.path.vo.Tree;

public class PathNode extends Tree<PathNode>{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path_node.id
     *
     * @mbg.generated Thu Jun 29 20:45:03 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path_node.name
     *
     * @mbg.generated Thu Jun 29 20:45:03 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path_node.path
     *
     * @mbg.generated Thu Jun 29 20:45:03 CST 2017
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column path_node.seq
     *
     * @mbg.generated Thu Jun 29 20:45:03 CST 2017
     */
    private Integer seq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path_node.id
     *
     * @return the value of path_node.id
     *
     * @mbg.generated Thu Jun 29 20:45:03 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path_node.id
     *
     * @param id the value for path_node.id
     *
     * @mbg.generated Thu Jun 29 20:45:03 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path_node.name
     *
     * @return the value of path_node.name
     *
     * @mbg.generated Thu Jun 29 20:45:03 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path_node.name
     *
     * @param name the value for path_node.name
     *
     * @mbg.generated Thu Jun 29 20:45:03 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path_node.path
     *
     * @return the value of path_node.path
     *
     * @mbg.generated Thu Jun 29 20:45:03 CST 2017
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path_node.path
     *
     * @param path the value for path_node.path
     *
     * @mbg.generated Thu Jun 29 20:45:03 CST 2017
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column path_node.seq
     *
     * @return the value of path_node.seq
     *
     * @mbg.generated Thu Jun 29 20:45:03 CST 2017
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column path_node.seq
     *
     * @param seq the value for path_node.seq
     *
     * @mbg.generated Thu Jun 29 20:45:03 CST 2017
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }
}